name: hedieaty
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  path: ^1.9.0
  sqflite: ^2.0.0+4
  firebase_storage: ^12.3.6
  connectivity_plus: ^4.0.0
  crypto: ^3.0.0
  awesome_notifications: ^0.10.0
  googleapis:
  googleapis_auth:
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
#  flutter_local_notifications: ^13.0.0
#  flutter_local_notifications: ^9.1.5
#  firebase_core: ^1.10.6
#  cloud_firestore: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/pp_1.jpg
    - asset/pp_2.jpg
    - asset/pp_3.jpg
    - asset/pp_4.jpg
    - asset/pp_5.jpg
    - asset/pp_6.jpg
    - asset/pp_7.jpg
    - asset/pp_8.jpg
    - asset/pp_9.jpg
    - asset/present.jpg
    - asset/signup.jpg
    - asset/offline.jpg
    - asset/profile.jpg
    - asset/necklace.jpg
    - asset/novel_science_fiction.jpg
    - asset/smart_watch.jpg


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Lobster
       fonts:
         - asset: asset/Lobster-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: Caveat
       fonts:
         - asset: asset/Caveat-VariableFont_wght.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
